# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - rfn

on:
  push:
    branches:
      - linux-appservice
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://ghcr.io/mehdi-mameri/wordpress/
        username: ${{ secrets.AzureAppService_ContainerUsername_2084f5fd8a144a56b0c2c420c2584f0a }}
        password: ${{ secrets.AzureAppService_ContainerPassword_cfc28164007b462a8c316b0b99b403f0 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ghcr.io/mehdi-mameri/wordpress/${{ secrets.AzureAppService_ContainerUsername_2084f5fd8a144a56b0c2c420c2584f0a }}/appwordpress-alpine-php:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'rfn'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_43e2f22767484576ac05186e96a8a1ce }}
        images: 'ghcr.io/mehdi-mameri/wordpress/${{ secrets.AzureAppService_ContainerUsername_2084f5fd8a144a56b0c2c420c2584f0a }}/appwordpress-alpine-php:${{ github.sha }}'